apiVersion: v1
kind: Service
metadata:
  name: project-fetcher
  labels:
    app: project-fetcher
spec:
  type: ClusterIP
  selector:
    app: project-fetcher
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
