apiVersion: v1
kind: Service
metadata:
  name: project-fetcher
  labels:
    app: project-fetcher
spec:
  type: ClusterIP
  selector:
    app: project-fetcher
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
